[project]
name = "crawler-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.4.0",
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "scrapy>=2.12.0",
    "sqlmodel>=0.0.22",
    "trio>=0.28.0",
]
